# Site settings
title: Portugal
client:
  name: Ein Ort, der Sehnsucht weckt
  link: "https://www.visitportugal.com/de"
core-se-link: https://www.secretescapes.de/aktuelle-angebote?utm_source=SE&utm_medium=hub&utm_campaign=italy_DE_2018
description: >
  Begeben Sie sich auf die Spuren der Etrusker, finden Sie einzigartige Relikte vergangener Zeiten wie die apulischen Trulli, erleben Sie das authentische Flair italienischer Dörfer in kleinen Borghi oder spüren Sie beim Genuss der Cucina italiana das mediterrane Lebensgefühl

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/portugal-2019" # the subpath of your site, e.g. /blog/
img:     "/de/portugal-2019/_assets/img"
css:     "/de/portugal-2019/_assets/css"
js:      "/de/portugal-2019/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
